/**
 * Mock Vendor Data
 * @description Temporary mock data to simulate vendor search results
 */

export const mockVendors = [
  {
    id: 1,
    name: 'Ernst & Young',
    logo: 'EY',
    category: 'Finance & Accounting',
    location: 'United Kingdom',
    rating: 4.5,
    tier: 'Tier 1',
    description: 'EY builds a better working world, helping create long-term value for clients, people and society and build trust in the capital markets.',
    specialty: 'FinTech',
    startFrom: '$50k',
  },
  {
    id: 2,
    name: 'PricewaterhouseCoopers (PwC)',
    logo: 'PwC',
    category: 'Business Solutions',
    location: 'United Kingdom',
    rating: 4.5,
    tier: 'Tier 1',
    description: 'PricewaterhouseCoopers International Limited is a British multinational professional services brand of firms, operating as partnerships under the PwC brand.',
    specialty: 'Consulting',
    startFrom: '$50k',
  },
  {
    id: 3,
    name: 'Accenture',
    logo: 'A',
    category: 'Software & IT',
    location: 'United States',
    rating: 4.5,
    tier: 'Tier 1',
    description: 'Accenture plc is an American-Irish multinational professional services company headquartered in Dublin for tax reasons, specializing in IT services and consulting.',
    specialty: 'Development',
    startFrom: '$50k',
  },
  {
    id: 4,
    name: 'Slalom',
    logo: 'S',
    category: 'Business Solutions',
    location: 'United States',
    rating: 4.5,
    tier: 'Tier 2',
    description: 'Slalom is a business and technology consulting firm headquartered in Seattle, Washington.',
    specialty: 'Finance',
    startFrom: '$25k',
  },
  {
    id: 5,
    name: 'Dynatrace',
    logo: 'D',
    category: 'Software Solutions',
    location: 'United Kingdom',
    rating: 4.5,
    tier: 'Tier 2',
    description: 'Dynatrace\'s software platform combines observability, business analytics and security data at scale to capture and retain data for every transaction.',
    specialty: 'FinTech',
    startFrom: '$15k',
  },
  {
    id: 6,
    name: 'Smartly',
    logo: 'SM',
    category: 'Software Solutions',
    location: 'United Kingdom',
    rating: 4.5,
    tier: 'Tier 2',
    description: 'Smartly, trusted by brands like Uber and eBay, is an AI-powered marketing and advertising technology specialized in social media advertising.',
    specialty: 'Product',
    startFrom: '$10k',
  },
];
